# Generated by Django 3.0.7 on 2020-07-06 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('represante', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('propietario', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Aprobado'), ('E', 'En espera de reingreso'), ('R', 'En revision')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=10)),
                ('fraccionamiento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('folio', models.CharField(max_length=13)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('oficio', models.CharField(max_length=14)),
                ('fecha_respuesta', models.DateField()),
                ('ingreso', models.IntegerField()),
                ('observaciones', models.CharField(max_length=300)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Desarrolladora')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Expediente')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL)),
                ('revisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisador', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Estados')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.SubCategorias')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_m3_seg', models.IntegerField()),
                ('vivienda', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Proyectos')),
            ],
        ),
    ]
