# Generated by Django 2.2 on 2020-08-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desarrolladora',
            old_name='represante',
            new_name='representante',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='oficio',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='status',
        ),
        migrations.AddField(
            model_name='estados',
            name='nombre',
            field=models.CharField(default='En revision', max_length=50),
        ),
        migrations.AlterField(
            model_name='estados',
            name='status',
            field=models.CharField(default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.IntegerField()),
                ('folio', models.CharField(max_length=13)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('oficio', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Proyectos')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('tipo', models.CharField(max_length=30)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Ingresos')),
            ],
        ),
    ]
