# Generated by Django 3.0.7 on 2020-07-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
