# Generated by Django 3.0.7 on 2020-07-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0002_auto_20200706_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.CharField(max_length=11),
        ),
    ]
