# Generated by Django 3.0.7 on 2020-07-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0003_auto_20200708_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desarrolladora',
            old_name='represante',
            new_name='representante',
        ),
    ]
