# Generated by Django 3.0.7 on 2020-07-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0004_auto_20200708_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='oficio',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
