# Generated by Django 3.0.7 on 2020-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0007_proyectos_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='nombre',
            field=models.CharField(default='En revision', max_length=50),
        ),
        migrations.AlterField(
            model_name='estados',
            name='status',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
