# Generated by Django 3.0.7 on 2020-07-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0008_auto_20200721_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='oficio',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='status',
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=13)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('oficio', models.CharField(blank=True, max_length=14, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('ingreso', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Proyectos')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Estados')),
            ],
        ),
    ]
