# Generated by Django 3.0.7 on 2020-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0010_auto_20200722_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='ingreso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
