# Generated by Django 3.0.7 on 2020-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0011_ingresos_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='observaciones',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
