# Generated by Django 3.0.7 on 2020-07-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0012_auto_20200724_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='observaciones',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddi.Ingresos')),
            ],
        ),
    ]
