# Generated by Django 3.0.7 on 2020-07-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddi', '0013_auto_20200724_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='tipo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
